// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    { type: "autogenerated", dirName: "home" },
    {
      type: 'link',
      label: 'Paima Studios Website',
      href: 'https://paimastudios.com',
    },
  ],
};

module.exports = sidebars;
